language: android
sudo: false
env:
  global:
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=24.0.1
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_NDK=android-ndk-r10e

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL

before_install:
  - curl -L http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O
  - chmod u+x android-ndk-r10e-linux-x86_64.bin
  - ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - rm android-ndk-r10e-linux-x86_64.bin

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window -no-boot-anim -cpu-delay 0 &
  - android-wait-for-emulator

script:
  - $ANDROID_NDK/ndk-build APP_ABI=$ANDROID_ABI
  - ant test
